[package]
name = "simp"
version = "1.5.3"
authors = ["Axel Kappel <axel.e.kappel@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "The (s)imple (im)age (p)rogram"
repository = "https://github.com/Kl4rry/simp"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "1.2.1"
cgmath = "0.18.0"
clipboard = "0.5"
glium = "0.29"
image = "0.23.14"
image_loader = { path = "./image_loader" }
imgui = "0.7.0"
imgui-glium-renderer = "0.7.0"
imgui-winit-support = "0.7.0"
lazy_static = "1.4.0"
msgbox = "0.6.0"
timing = "0.2.1"
tinyfiledialogs = "3.3.10"
util = { path = "./util" }
vec2 = { path = "./vec2" }
webbrowser = "0.5.5"

[target.'cfg(windows)'.dependencies]
native-windows-gui = "1.0.12"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[package.metadata.winres]
OriginalFilename = "simp.exe"
FileDescription = "Simp"
LegalCopyright = "Copyright © 2021 Axel Kappel"
ProductName = "Simp"

[workspace]
members = [
    "image_loader",
    "util",
    "vec2",
]
