[package]
name = "simp"
version = "2.0.0"
authors = ["Axel Kappel <axel.e.kappel@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "The (s)imple (i)mage (m)anipulation (p)rogram"
repository = "https://github.com/Kl4rry/simp"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "1.2.1"
cgmath = "0.18.0"
clipboard = "0.5"
ctrlc = "3.2.0"
directories = "4.0.1"
glium = "0.30.0"
image = "0.23.14"
image_io = { path = "./image_io", version = "0.1.0" }
imgui = "0.8.0"
imgui-glium-renderer = "0.8.0"
imgui-winit-support = "0.8.0"
lazy_static = "1.4.0"
lru = "0.6.6"
msgbox = "0.6.0"
rect = { path = "./rect", version = "0.1.0" }
rfd = "0.4.0"
ron = "0.6.5"
serde = "1.0.130"
serde_derive = "1.0.130"
timing = "0.2.1"
trash = "2.0"
util = { path = "./util", version = "0.1.0" }
vec2 = { path = "./vec2", version = "0.1.0" }
webbrowser = "0.5.5"
winit = "0.24.0"

[target.'cfg(windows)'.dependencies]
native-windows-gui = "1.0.12"
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[package.metadata.winres]
OriginalFilename = "simp.exe"
FileDescription = "Simp"
LegalCopyright = "Copyright © 2021 Axel Kappel"
ProductName = "Simp"

[workspace]
members = [
    "image_io",
    "rect",
    "util",
    "vec2",
]

[profile.release]
lto = true

[profile.dev]
opt-level = 3
