[package]
name = "simp"
version = "2.0.3"
authors = ["Axel Kappel <axel.e.kappel@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "The simple image manipulation program"
repository = "https://github.com/Kl4rry/simp"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "2.1.0"
cgmath = "0.18.0"
confy = "0.4.0"
ctrlc = "3.2.0"
egui = "0.17.0"
egui_glium = "0.17.0"
glium = "0.31.0"
image = "0.24.1"
imagepipe = "0.4.0"
lazy_static = "1.4.0"
libwebp = "0.1.2"
lru = "0.7.3"
msgbox = "0.7.0"
nanoid = "0.4.0"
psd = "0.3.0"
rawloader = "0.37.0"
resvg = "0.22.0"
rexif = "0.7.3"
rfd = "0.8.1"
serde = { version = "1", features = ["derive"] }
tiny-skia = "0.6.3"
trash = "2.0"
usvg = "0.22.0"
webbrowser = "0.6.0"
webp-animation = "0.5.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = { version = "0.3.9", features = ["everything"] }

[package.metadata.winres]
OriginalFilename = "simp.exe"
FileDescription = "Simp"
LegalCopyright = "Copyright © 2021 Axel Kappel"
ProductName = "Simp"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 3

[features]
default = []
avif = ["image/avif-decoder"]
