[package]
name = "simp"
version = "0.1.2"
edition = "2018"
license = "Apache-2.0"
description = "The (s)imple (im)age (p)rogram"
repository = "https://github.com/Kl4rry/simp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5"
glium = { version = "0.29", default-features = true }
image = "0.23.14"
imgui = "0.7.0"
imgui-glium-renderer = "0.7.0"
imgui-winit-support = "0.7.0"
tinyfiledialogs = "3.3.10"
timing = "0.2.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[package.metadata.winres]
OriginalFilename = "simp.exe"
FileDescription = "Simp"
LegalCopyright = "Copyright © 2021 Axel Kappel"
ProductName = "Simp"